GROQ_API_KEY = "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"
SUPABASE_URL = "https://isxykyawirffuarbmwsc.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzeHlreWF3aXJmZnVhcmJtd3NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjE0MjE3MTcsImV4cCI6MjAzNjk5NzcxN30.-dUat7yc7wb0-h5R_SmTnX29pWJNGsMxkgyzCfNImhA"
NGROK_AUTH_TOKEN = "2jIacNXA5dgxIVeubUknjFB5ZSO_6vsajcqEiGrGtLgEJTTMc"
